source "https://rubygems.org"

gem "rails", "~> 8.0.5", ">= 8.0.5.1"
# json 3.0 drops quirks_mode; Rails 8.0.5.1 still passes it (fixed on later 8.0)
gem "json", "~> 2.10"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.9"
gem "rack-cors"
gem "rack-attack"
gem "redis", ">= 4.0.1"
gem "sidekiq", "~> 7.3"
gem "sidekiq-cron", "~> 1.12"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "timecop"
end
